### ISSUE TITLE
Timeout on UpdateAndCommitAsync()

### ISSUE THREAD

**Issue by hexpl0it** [firesharkstudios/butterfly-server-dotnet#9]
I'm trying to run the Database example. I use a SqlServer but when i try to do the UpdateAndCommitAsync() an execption throw up.

  ``` 
 // This will echo multiple Update data events to the Console because it impacts multiple records in the resultset
 // Yes, that's pretty cool :)
 Console.WriteLine("Updating user name to 'Mr. Spongebob'");
 await database.UpdateAndCommitAsync("users", new
 {
          id = spongebobId,
          name = "Mr. Spongebob"
});
await Task.Delay(500);  
```

This is the stack trace.

  ```
 at Butterfly.SqlServer.SqlServerDatabase.ExecuteCommandAsync[T](Func`2 query, String executableSql, Dictionary`2 executableParams) in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.SqlServer\SqlServerDatabase.cs:line 268
   at Butterfly.SqlServer.SqlServerDatabase.DoSelectRowsAsync(String executableSql, Dictionary`2 executableParams, Int32 limit) in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.SqlServer\SqlServerDatabase.cs:line 73
   at Butterfly.Core.Database.Dynamic.DynamicView.GetImpactedRecordsAsync(KeyValueDataEvent keyValueDataEvent) in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.Core\Database\Dynamic\DynamicView.cs:line 252
   at Butterfly.Core.Database.Dynamic.DynamicViewSet.StoreImpactedRecordsInDataEventTransaction(TransactionState transactionState, DataEventTransaction dataEventTransaction) in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.Core\Database\Dynamic\DynamicViewSet.cs:line 115
   at Butterfly.Core.Database.Dynamic.DynamicViewSet.ProcessUncommittedDataEventTransactionAsync(DataEventTransaction dataEventTransaction) in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.Core\Database\Dynamic\DynamicViewSet.cs:line 100
   at Butterfly.Core.Database.BaseDatabase.PostDataEventTransactionAsync(TransactionState transactionState, DataEventTransaction dataEventTransaction) in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.Core\Database\BaseDatabase.cs:line 147
   at Butterfly.Core.Database.BaseTransaction.CommitAsync() in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.Core\Database\BaseTransaction.cs:line 258
   at Butterfly.Core.Database.BaseDatabase.UpdateAndCommitAsync(String updateStatement, Object vars) in C:\Users\marcoc\Desktop\butterfly-server-dotnet-master\Butterfly.Core\Database\BaseDatabase.cs:line 257
   at ConsoleApp1.Program.Run(IDatabase database) in c:\users\marcoc\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 151
```

**Comment by johan-v-r** [comment]
Which version of SQL Server are you running?
Also thanks for the stack trace, but please provide the rest of the exception as well. Hopefully something useful in there.

**Comment by johan-v-r** [comment]
Could you possibly try to set your [Isolation Level](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/snapshot-isolation-in-sql-server) just to see if that solves the problem?

```sql
ALTER DATABASE MyDatabase  
SET ALLOW_SNAPSHOT_ISOLATION ON  
  
ALTER DATABASE MyDatabase  
SET READ_COMMITTED_SNAPSHOT ON
```
